trigger:
  branches:
    include:
      - develop
      - MANGO-387

pool:
  vmImage: 'ubuntu-20.04'

variables:
  - group: MANGO_INTEGRATION_TESTS
  solution: 'MangoAPI.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
  - task: NuGetToolInstaller@1
    displayName: 'Install Nuget'

  - task: NuGetCommand@2
    displayName: 'Restore Nuget Packages'
    inputs:
      restoreSolution: '$(solution)'

  - task: DotNetCoreCLI@2
    displayName: 'dotnet build $(buildConfiguration)'
    inputs:
      command: 'build'
      arguments: '--configuration $(buildConfiguration)'

  - task: VSTest@2
    displayName: 'Run tests'
    inputs:
      platform: '$(buildPlatform)'
      configuration: '$(buildConfiguration)'
