trigger:
  branches:
    include:
      - develop
      - MANGO-387

pool:
  vmImage: 'ubuntu 20.04'

variables:
  buildConfiguration: 'Release'

stages:
  - stage: 'Build_Test'
    displayName: 'Build/Test'
    jobs:
      - job: 'Build'
        displayName: 'Build/Test'

        variables:
          - group: MANGO_INTEGRATION_TESTS
          - name: solutionProjectPath
            value: 'MangoAPI.sln'

          - name: integrationTestProjectPath
            value: 'MangoAPI.Tests/MangoAPI.Tests.csproj'

          - name: buildPlatform
            value: 'Any CPU'

        steps:
          - template: azure-pipelines-common.yml