version: "3.9"

networks:
  mangonetwork:
    driver: bridge

services:
  mango-backend:
    container_name: mango-backend-compose
    depends_on:
      - "mango-mssql-db"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4040:443"
      - "8000:80"
    environment:
      MANGO_JWT_ISSUER: "http://localhost:4200"
      MANGO_JWT_AUDIENCE: "https://localhost:5001"
      MANGO_JWT_SIGN_KEY: "00b01c41-074a-4949-85dc-31658e2e2a8c"
      MANGO_EMAIL_NOTIFICATIONS_ADDRESS: "mango.messenger.notify@gmail.com"
      MANGO_FRONTEND_ADDRESS: "http://localhost:4200/"
      MANGO_DATABASE_URL: "Server=mango-mssql-db;Database=MANGO_DEV;User Id=sa;Password=x2yiJt!Fs;TrustServerCertificate=true;"
      MANGO_SEED_PASSWORD: ${MANGO_SEED_PASSWORD}
      MANGO_BLOB_URL: ${MANGO_BLOB_URL}
      MANGO_BLOB_CONTAINER: ${MANGO_BLOB_CONTAINER}
      MANGO_BLOB_ACCESS: ${MANGO_BLOB_ACCESS}
      MANGO_MAILGUN_API_KEY: ${MANGO_MAILGUN_API_KEY}
      MANGO_MAILGUN_API_BASE_URL: ${MANGO_MAILGUN_API_BASE_URL}
      MANGO_MAILGUN_API_DOMAIN: ${MANGO_MAILGUN_API_DOMAIN}
    networks:
      - mangonetwork

  mango-mssql-db:
    image: mcr.microsoft.com/mssql/server:latest
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "x2yiJt!Fs"
    networks:
      - mangonetwork