version: "3.4"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      DATABASE_URL: "Server=db;Database=MANGO_DOCKER_COMPOSE;User Id=sa;Password=x2yiJt!Fs;TrustServerCertificate=true;"
    depends_on:
      - db
  
  db:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    ports:
      - "1444:1433"
    
    environment:
      SA_PASSWORD: "x2yiJt!Fs"
      ACCEPT_EULA: "Y"