version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
      - "5001:443"
    environment:
      - DatabaseUrl=Server=db;Database=MANGO_DOCKER_COMPOSE;User Id=sa;Password=x2yiJt!Fs;TrustServerCertificate=true;
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/MangoAPI.Presentation.pfx
      - BlobUrl=AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;DefaultEndpointsProtocol=http;BlobEndpoint=http://host.docker.internal:10000/devstoreaccount1;QueueEndpoint=http://host.docker.internal:10001/devstoreaccount1;TableEndpoint=http://host.docker.internal:10002/devstoreaccount1;
    volumes:
      - ~/.aspnet/https:/https:ro
    depends_on:
      - db
      - storage
  
  db:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    ports:
      - "1444:1433"
    environment:
      SA_PASSWORD: "x2yiJt!Fs"
      ACCEPT_EULA: "Y"
  
  storage:
    image: mcr.microsoft.com/azure-storage/azurite
    command: "azurite --blobHost 0.0.0.0 --blobPort 10000 --queueHost 0.0.0.0 --queuePort 10001 --location /workspace --debug /workspace/debug.log"
    hostname: azurite
    restart: always
    ports:
      - 10000:10000
      - 10001:10001