name: Azure Dev VM SSH Deploy

on:
  push:
    branches:
      - azure-dev
  
  workflow_dispatch:
    branches:
      - azure-dev

jobs:
  build:
    name: Azure_Dev_VM_SSH_Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core 6.0 SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Build .NET Project Configuration Release
        run: dotnet build --configuration Release

      - name: Publish .NET Project
        run: |
          dotnet restore
          dotnet publish "MangoAPI.Presentation/MangoAPI.Presentation.csproj" -r linux-x64 -o mango-linux-build/src

      - name: Create Artifact
        run: |
          cd mango-linux-build/src
          zip -r mango-artifact.zip .

      - name: Stop Ubuntu VM service via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AZURE_DEV_SSH_HOST }}
          username: ${{ secrets.AZURE_DEV_SSH_USER }}
          key: ${{ secrets.AZURE_DEV_SSH_KEY }}
          script: |
            sudo systemctl stop mangoback

      - name: Copy Release files to  the Ubuntu VM via SSH
        uses: nogsantos/scp-deploy@master
        with:
          src: mango-linux-build/src/mango-artifact.zip
          host: ${{ secrets.AZURE_DEV_SSH_HOST }}
          remote: "mango-backend"
          port: 22
          user: ${{ secrets.AZURE_DEV_SSH_USER }}
          key: ${{ secrets.AZURE_DEV_SSH_KEY }}

      - name: Unzip Artifact on VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AZURE_DEV_SSH_HOST }}
          username: ${{ secrets.AZURE_DEV_SSH_USER }}
          key: ${{ secrets.AZURE_DEV_SSH_KEY }}
          script: unzip -o ~/mango-backend/mango-artifact.zip -d ~/mango-backend

      - name: Start Ubuntu VM service via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AZURE_DEV_SSH_HOST }}
          username: ${{ secrets.AZURE_DEV_SSH_USER }}
          key: ${{ secrets.AZURE_DEV_SSH_KEY }}
          script: sudo systemctl start mangoback