name: Azure Deploy

on: 
  push:
    branches:
      - MANGO-264

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Release application Linux x64
      run: | 
        ls -l
        dotnet publish "MangoAPI.Presentation/MangoAPI.Presentation.csproj" -r linux-x64 -o /mango-linux-build/src
        ssh -i ${{ secrets.AZURE_SSH_KEY }} razumovsky_r@mangoback.sveshnikov.work "sudo systemctl stop mangoback.service"
        scp -r -i ${{ secrets.AZURE_SSH_KEY }} /mango-linux-build/src/* razumovsky_r@mangoback.sveshnikov.work:/home/razumovsky_r/mango-backend
        ssh -i ${{ secrets.AZURE_SSH_KEY }} razumovsky_r@mangoback.sveshnikov.work "sudo systemctl start mangoback.service"