name: Build

on:
  push:
    branches:
      - develop
      - azure-dev
      - azure-qa
      - master
      - MANGO-435
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [ 16.x ]
    
    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Node Modules
        run: |
          cd ./MangoAPI.Client
          npm ci

      - name: Build Angular Project (Production)
        run: |
          cd ./MangoAPI.Client
          npm run build --production

      - name: Lint Angular Project
        run: |
          cd ./MangoAPI.Client
          npm run lint

      - name: Restore Nuget Packages
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore /p:ContinuousIntegrationBuild=true

      - name: Run Unit Tests
        run: dotnet test MangoAPI.Tests/MangoAPI.Tests.csproj --no-build --verbosity normal /p:CollectCoverage=true /p:Exclude="[*DataAccess]*" /p:CoverletOutputFormat=opencover
        env:
          MANGO_SEED_PASSWORD: ${{ secrets.MANGO_SEED_PASSWORD }}
          MANGO_JWT_SIGN_KEY: ${{ secrets.MANGO_JWT_SIGN_KEY }}
          MANGO_BLOB_CONTAINER: ${{ secrets.MANGO_BLOB_CONTAINER }}
          MANGO_BLOB_ACCESS: ${{ secrets.MANGO_BLOB_ACCESS }}

      - name: Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: web, server
          fail_ci_if_error: false
          verbose: true

      - name: Run automated unit and integration tests
        run: dotnet test MangoAPI.Tests/MangoAPI.Tests.csproj  /p:CollectCoverage=true /p:CoverletOutput=TestResults/ /p:CoverletOutputFormat=lcov
        env:
          MANGO_SEED_PASSWORD: ${{ secrets.MANGO_SEED_PASSWORD }}
          MANGO_JWT_SIGN_KEY: ${{ secrets.MANGO_JWT_SIGN_KEY }}
          MANGO_BLOB_CONTAINER: ${{ secrets.MANGO_BLOB_CONTAINER }}
          MANGO_BLOB_ACCESS: ${{ secrets.MANGO_BLOB_ACCESS }}

      - name: Publish coverage report to coveralls.io
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: MangoAPI.Tests/TestResults/coverage.info