name: Build Angular

on:
  push:
    branches:
      - develop
      - master

  pull_request:
    branches: [ develop ]

  workflow_dispatch:

jobs:
  build-angular:
    name: Build Angular
    runs-on: ${{ matrix.environment }}
    strategy:
      matrix:
        environment:
          - ubuntu-latest
          - windows-latest

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3

      - name: 'Setup Node.js 16.3.1'
        uses: actions/setup-node@v3
        with:
          node-version: '16.3.1'
          cache: 'npm'
          cache-dependency-path: 'MangoAPI.Client/package-lock.json'
          
      - name: 'Use node 16.3.1'
        run: nvm use 16.3.1
        
      - name: 'Print current node version'
        run: node -v
        
      - name: 'Print current npm version'
        run: npm -v

      - name: 'Npm ci'
        working-directory: './MangoAPI.Client'
        run: npm ci
        
      - name: 'Install angular cli 15.2.2'
        run: npm install -g @angular/cli@15.2.2
        
      - name: 'Print current angular cli version'
        run: ng version

      - name: 'Angular build'
        working-directory: './MangoAPI.Client'
        run: ng build

      - name: 'Drop artifact'
        uses: actions/upload-artifact@v3
        with:
          name: 'angular-build'
          path: './MangoAPI.Presentation/wwwroot'
