name: Run CNG DH Handshake

on:
  workflow_dispatch:

jobs:
  run-cng-dh-handshake:
    runs-on: windows-latest
    
    steps:
      - name: 📝 Fetch Sources 📝
        uses: actions/checkout@v2

      - name: 🔄 Restore Nuget Packages 🔄
        run: dotnet restore

      - name: 🛠 Build .NET Solution 🛠
        run: dotnet build --no-restore /p:ContinuousIntegrationBuild=true

      - name: 🔓 Alice (Sender) Creates Key Exchange Request to Bob 🔓
        shell: powershell
        run: |
          Set-Location "MangoAPI.DiffieHellmanConsole/bin/Debug/net6.0"
          dotnet MangoAPI.DiffieHellmanConsole.dll login $env:SENDER_EMAIL $env:SENDER_PASSWORD
          dotnet MangoAPI.DiffieHellmanConsole.dll cng-generate-private-key $env:RECEIVER_ID
          dotnet MangoAPI.DiffieHellmanConsole.dll cng-create-key-exchange $env:RECEIVER_ID
        env:
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
          MANGO_API_ADDRESS: ${{ secrets.MANGO_API_ADDRESS }}
          RECEIVER_ID: ${{ secrets.RECEIVER_ID }}

      - name: 🤝 Bob (Receiver) confirms Key Exchange Request with Alice 🤝
        shell: powershell
        run: |
          Set-Location "MangoAPI.DiffieHellmanConsole/bin/Debug/net6.0"
          dotnet MangoAPI.DiffieHellmanConsole.dll login $env:RECEIVER_EMAIL $env:RECEIVER_PASSWORD
          dotnet MangoAPI.DiffieHellmanConsole.dll cng-generate-private-key $env:SENDER_ID
          dotnet MangoAPI.DiffieHellmanConsole.dll cng-print-key-exchanges
          dotnet MangoAPI.DiffieHellmanConsole.dll cng-confirm-key-exchange $env:SENDER_ID
        env:
          RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}
          RECEIVER_PASSWORD: ${{ secrets.RECEIVER_PASSWORD }}
          MANGO_API_ADDRESS: ${{ secrets.MANGO_API_ADDRESS }}
          SENDER_ID: ${{ secrets.SENDER_ID }}

      - name: 🔑 Bob (Receiver) derives the Common Secret 🔑
        shell: powershell
        run: |
          Set-Location "MangoAPI.DiffieHellmanConsole/bin/Debug/net6.0"
          dotnet MangoAPI.DiffieHellmanConsole.dll cng-download-public-key --receiver $env:SENDER_ID
          dotnet MangoAPI.DiffieHellmanConsole.dll cng-create-common-secret --receiver $env:SENDER_ID
        env:
          MANGO_API_ADDRESS: ${{ secrets.MANGO_API_ADDRESS }}
          SENDER_ID: ${{ secrets.SENDER_ID }}

      - name: 🔑 Alice (Sender) derives the Common Secret 🔑
        shell: powershell
        run: |
          Set-Location "MangoAPI.DiffieHellmanConsole/bin/Debug/net6.0"
          dotnet MangoAPI.DiffieHellmanConsole.dll login $env:SENDER_EMAIL $env:SENDER_PASSWORD
          dotnet MangoAPI.DiffieHellmanConsole.dll cng-print-key-exchanges
          dotnet MangoAPI.DiffieHellmanConsole.dll cng-download-public-key --sender $env:RECEIVER_ID
          dotnet MangoAPI.DiffieHellmanConsole.dll cng-create-common-secret --sender $env:RECEIVER_ID
        env:
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
          MANGO_API_ADDRESS: ${{ secrets.MANGO_API_ADDRESS }}
          RECEIVER_ID: ${{ secrets.RECEIVER_ID }}

      - name: ✅ Validate the Common Secret ✅
        shell: powershell
        run: |
          Set-Location "MangoAPI.DiffieHellmanConsole/bin/Debug/net6.0"
          dotnet MangoAPI.DiffieHellmanConsole.dll cng-validate-common-secret $env:SENDER_ID $env:RECEIVER_ID
        env:
          MANGO_API_ADDRESS: ${{ secrets.MANGO_API_ADDRESS }}
          RECEIVER_ID: ${{ secrets.RECEIVER_ID }}
          SENDER_ID: ${{ secrets.SENDER_ID }}