name: Run Build and Test (.NET, Angular)

on:
  push:
    branches:
      - develop
      - azure-dev
      - azure-qa
      - master
  pull_request:
    branches:
      - develop
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: 📝 Fetch Sources 📝
        uses: actions/checkout@v2

      - name: ⚙ Setup .NET 6.0 SDK ⚙
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: ⚙ Setup Node.js 16.x ⚙
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: 🔃 Install Node Modules 🔃
        run: |
          cd ./MangoAPI.Client
          npm ci

      - name: 🛠 Build Angular Project (Production) 🛠
        run: |
          cd ./MangoAPI.Client
          npm run build --production

      - name: 🔆 Lint Angular Project 🔆
        run: |
          cd ./MangoAPI.Client
          npm run lint

      - name: 🔄 Restore Nuget Packages 🔄
        run: dotnet restore

      - name: 🛠 Build .NET Solution 🛠
        run: dotnet build --no-restore /p:ContinuousIntegrationBuild=true

      - name: ✅ Run Unit Tests (for Codecov) ✅
        run: dotnet test MangoAPI.Tests/MangoAPI.Tests.csproj --no-build --verbosity normal /p:CollectCoverage=true /p:Exclude="[*DataAccess]*" /p:CoverletOutputFormat=opencover
        env:
          MANGO_SEED_PASSWORD: ${{ secrets.MANGO_SEED_PASSWORD }}
          MANGO_JWT_SIGN_KEY: ${{ secrets.MANGO_JWT_SIGN_KEY }}
          MANGO_BLOB_CONTAINER: ${{ secrets.MANGO_BLOB_CONTAINER }}
          MANGO_BLOB_ACCESS: ${{ secrets.MANGO_BLOB_ACCESS }}

      - name: ✴ Publish coverage report to Codecov ✴
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: web, server
          fail_ci_if_error: false
          verbose: true

      - name: ✅ Run Unit Tests (for Coveralls) ✅
        run: dotnet test MangoAPI.Tests/MangoAPI.Tests.csproj  /p:CollectCoverage=true /p:CoverletOutput=TestResults/ /p:CoverletOutputFormat=lcov
        env:
          MANGO_SEED_PASSWORD: ${{ secrets.MANGO_SEED_PASSWORD }}
          MANGO_JWT_SIGN_KEY: ${{ secrets.MANGO_JWT_SIGN_KEY }}
          MANGO_BLOB_CONTAINER: ${{ secrets.MANGO_BLOB_CONTAINER }}
          MANGO_BLOB_ACCESS: ${{ secrets.MANGO_BLOB_ACCESS }}

      - name: ✨ Publish coverage report to Coveralls ✨
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: MangoAPI.Tests/TestResults/coverage.info