name: Run CNG DH Handshake

on:
  push:
    branches: [ MANGO-520 ]
  workflow_dispatch:

jobs:
  run-cng-dh-handshake:
    runs-on: windows-latest
    name: Run CNG Diffie-Hellman Handshake
    steps:
      - name: 📝 Fetch Sources 📝
        uses: actions/checkout@v2

      - name: ⚙ Setup .NET 6.0 SDK ⚙
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: 🔄 Restore Nuget Packages 🔄
        run: |
          dotnet restore ./MangoAPI.DiffieHellmanLibrary/MangoAPI.DiffieHellmanLibrary.csproj
          dotnet restore ./MangoAPI.DiffieHellmanConsole/MangoAPI.DiffieHellmanConsole.csproj

      - name: 🛠 Build .NET Solution 🛠
        run: |
          dotnet build ./MangoAPI.DiffieHellmanLibrary/MangoAPI.DiffieHellmanLibrary.csproj --no-restore
          dotnet build ./MangoAPI.DiffieHellmanConsole/MangoAPI.DiffieHellmanConsole.csproj --no-restore

      - name: 🔓 Alice (Sender) Creates Key Exchange Request to Bob 🔓
        working-directory: ./MangoAPI.DiffieHellmanConsole/bin/Debug/net6.0
        shell: powershell
        run: |
          dotnet MangoAPI.DiffieHellmanConsole.dll login $env:SENDER_EMAIL $env:SENDER_PASSWORD
          dotnet MangoAPI.DiffieHellmanConsole.dll cng-generate-private-key $env:RECEIVER_ID
          dotnet MangoAPI.DiffieHellmanConsole.dll cng-create-key-exchange $env:RECEIVER_ID
        env:
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
          MANGO_API_ADDRESS: ${{ secrets.MANGO_API_ADDRESS }}
          RECEIVER_ID: ${{ secrets.RECEIVER_ID }}

      - name: 🤝 Bob (Receiver) confirms Key Exchange Request with Alice 🤝
        working-directory: ./MangoAPI.DiffieHellmanConsole/bin/Debug/net6.0
        shell: powershell
        run: |
          dotnet MangoAPI.DiffieHellmanConsole.dll login $env:RECEIVER_EMAIL $env:RECEIVER_PASSWORD
          dotnet MangoAPI.DiffieHellmanConsole.dll cng-generate-private-key $env:SENDER_ID
          dotnet MangoAPI.DiffieHellmanConsole.dll cng-print-key-exchanges
          dotnet MangoAPI.DiffieHellmanConsole.dll cng-confirm-key-exchange $env:SENDER_ID
        env:
          RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}
          RECEIVER_PASSWORD: ${{ secrets.RECEIVER_PASSWORD }}
          MANGO_API_ADDRESS: ${{ secrets.MANGO_API_ADDRESS }}
          SENDER_ID: ${{ secrets.SENDER_ID }}

      - name: 🔑 Bob (Receiver) derives the Common Secret 🔑
        working-directory: ./MangoAPI.DiffieHellmanConsole/bin/Debug/net6.0
        shell: powershell
        run: |
          dotnet MangoAPI.DiffieHellmanConsole.dll cng-download-public-key --receiver $env:SENDER_ID
          dotnet MangoAPI.DiffieHellmanConsole.dll cng-create-common-secret --receiver $env:SENDER_ID
        env:
          MANGO_API_ADDRESS: ${{ secrets.MANGO_API_ADDRESS }}
          SENDER_ID: ${{ secrets.SENDER_ID }}

      - name: 🔑 Alice (Sender) derives the Common Secret 🔑
        working-directory: ./MangoAPI.DiffieHellmanConsole/bin/Debug/net6.0
        shell: powershell
        run: |
          dotnet MangoAPI.DiffieHellmanConsole.dll login $env:SENDER_EMAIL $env:SENDER_PASSWORD
          dotnet MangoAPI.DiffieHellmanConsole.dll cng-print-key-exchanges
          dotnet MangoAPI.DiffieHellmanConsole.dll cng-download-public-key --sender $env:RECEIVER_ID
          dotnet MangoAPI.DiffieHellmanConsole.dll cng-create-common-secret --sender $env:RECEIVER_ID
        env:
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
          MANGO_API_ADDRESS: ${{ secrets.MANGO_API_ADDRESS }}
          RECEIVER_ID: ${{ secrets.RECEIVER_ID }}

      - name: ✅ Validate the Common Secret ✅
        working-directory: ./MangoAPI.DiffieHellmanConsole/bin/Debug/net6.0
        shell: powershell
        run: |
          dotnet MangoAPI.DiffieHellmanConsole.dll cng-validate-common-secret $env:SENDER_ID $env:RECEIVER_ID
        env:
          MANGO_API_ADDRESS: ${{ secrets.MANGO_API_ADDRESS }}
          RECEIVER_ID: ${{ secrets.RECEIVER_ID }}
          SENDER_ID: ${{ secrets.SENDER_ID }}
